CREATE DATABASE MYSQL_LEARNER;
SHOW DATABASES;
USE MYSQL_LEARNER;
CREATE TABLE PETSALE (
	ID INT NOT NULL,
    PET CHAR(20),
    SALEPRICE DECIMAL (6,2),
    PROFIT DECIMAL (6,2),
    SALE_DATE DATE
    );

CREATE TABLE PET (
	ID INT NOT NULL,
    ANIMAL VARCHAR(20),
    QUANTITY INT 
    );
    
